mode: "development" # development/production

ticker:
  interval: 3000 # ms

apiServer:
  addr: "localhost:8080"
  timeout: 0 # ms

tracer:
  enabled: false
  serviceName: "consumer"
  endpoint: "http://jaeger-collector.istio-system:14268/api/traces"
