@scheme=http
@url=localhost:8080
@apiPrefix=api/v1

################################################################################
# Liveness probe
################################################################################
GET {{scheme}}://{{url}}/liveness

################################################################################
# Readiness probe
################################################################################
GET {{scheme}}://{{url}}/readiness

################################################################################
# Say hello
################################################################################
GET {{scheme}}://{{url}}/{{apiPrefix}}/hello/Suhyuk
Content-Type: application/json
