apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "isp-user.fullname" . }}
  labels:
    {{- include "isp-user.labels" . | nindent 4 }}
data:
  release.yaml: |
    {{- toYaml .Values.app.config | nindent 4 }}
