apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "isp-user.fullname" . }}
  labels:
    {{- include "isp-user.labels" . | nindent 4 }}
data:
  release.yaml: |
    mode: {{ .Values.config.mode | quote }}
    http:
      host: {{ .Values.config.http.host | quote }}
      port: {{ .Values.config.http.port | quote }}
    tracer:
      enabled: {{ .Values.config.tracer.enabled }}
      serviceName: {{ .Values.config.tracer.serviceName | quote }}
      endpoint: {{ .Values.config.tracer.endpoint | quote }}