mode: "development" # development/production

http:
  host: "0.0.0.0"
  port: "8080"

userServer:
  addr: "localhost:32213"
  timeout: 3000 # ms

tracer:
  enabled: true
  serviceName: "api-server"
  endpoint: "http://jaeger-collector.istio-system:14268/api/traces"
