apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istio
spec:
  profile: minimal
  tag: 1.12.2
  meshConfig:
    accessLogFile: /dev/stdout
    enableTracing: true
    defaultConfig:
      tracing:
        sampling: 100.0
  components:
    ingressGateways:
      - name: istio-ingressgateway
        namespace: istio-ingress
        enabled: true
        label:
          istio: ingressgateway
        k8s:
          service:
            type: NodePort
            ports:
              - name: status-port
                port: 15021
                protocol: TCP
                nodePort: 30021
              - name: http2
                port: 80
                protocol: TCP
                nodePort: 30080
              - name: https
                port: 443
                protocol: TCP
                nodePort: 30443
          hpaSpec:
            minReplicas: 1
            maxReplicas: 5
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
            requests:
              cpu: 200m
              memory: 256Mi
