apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "isp-consumer.fullname" . }}
  labels:
    {{- include "isp-consumer.labels" . | nindent 4 }}
data:
  release.yaml: |
    mode: {{ .Values.config.mode | quote }}
    ticker:
      interval: {{ .Values.config.ticker.interval }}
    apiServer:
      addr: {{ .Values.config.apiServer.addr | quote }}
      timeout: {{ .Values.config.apiServer.timeout }}